export const Gstatus=['IN_APPROVAL', 'APPROVED','NOT_APPROVED',"PROCESSED","FAILED_PER","READY_FOR_TRANSFER","RECONCILIATION_PENDING","RECONCILIATION_FAILED"];
export const GReconciliatioStatus=['OPEN', 'FAILED','RECONCILED'];
export const GfileType=['PAIN_001_001_03', 'CAMT_054_001_08','PAIN_008','CAMT_054_001_02'];

export const pain002NCAMT053Status=["OPEN","RECONCILED", "FAILED"]




